- name: restart docker service
  systemd:
     name: "{{ item }}.service"
     enabled: true
     state: restarted
     daemon_reload: yes
  with_items:
    - "{{ restart_services | unique }}"

- name: restart timer service
  systemd:
     name: "{{ item }}.timer"
     enabled: true
     state: restarted
     daemon_reload: yes
  with_items:
    - "{{ timer_services }}"
