###################################################################################################

- name: wait

  when: ping

  become: false

  local_action: wait_for host={{ ping_host }}
                         port={{ ping_port }}
                      timeout={{ ping_wait }}
                        state=started

  tags:
    - ping

###################################################################################################

- name: execute

  when: ping

  raw: '{{ ping_command }}'

  tags:
    - ping

###################################################################################################
